- CONTRIBUTING.MD
- README.md
Updates the Stack Overflow tags to match https://stackoverflow.com/questions/tagged/ibm-secrets-manager.
> Update Stack Overflow tags

- package-lock.json
- package.json
https://github.ibm.com/security-services/secrets-manager-project-management/issues/3267
> upgrade dep vulnerabilities

- test/integration/secrets-manager.v1.test.js
Add Cleanup to Tests and enable parallel test runs
> Version 1.0.31

- package-lock.json
- package.json
- secrets-manager/v1.ts
- test/integration/secrets-manager.v1.test.js
- test/unit/secrets-manager.v1.test.js
> version 1.0.34 - locks

- package-lock.json
- package.json
- secrets-manager/v1.ts
- test/unit/secrets-manager.v1.test.js
New Features:
Custom-metadata handling
version-custom-metadata handling
UpdateVersionMetadata new API
> UpdateVersionMetadata new API

- package-lock.json
- package.json
- secrets-manager/v1.ts
create public cert - challenges added
Release 1.0.37
> create public cert - challenges added

- package-lock.json
- package.json
- secrets-manager/v1.ts
Signed-off-by: haims <haims@il.ibm.com>
> User-provided CSR

- .github/workflows/create-release.yaml
> Refactor workflow

- .releaserc
return to the original SDK team releaserc file
> release: revert to OG releaserc file

- .github/workflows/create-release.yaml
- .releaserc
add release notes functionality to semantic-release
> Test workflow

- CHANGELOG.md
- CONTRIBUTING.MD
- README.md
- lib/common.ts
- package-lock.json
- package.json
- secrets-manager/v1.ts
- test/unit/common.test.js
1. align the repo with the release tag
2. align the rename of the repo
> release: align repo with release tag and renaming

- package-lock.json
- package.json
Update IBM core SDK version to latest version.
> release: Update core SDK

- README.md
update core-sdk package and dependencies
> release: update dependencies

- package-lock.json
- package.json
This PR fixes #105 by updating `package.json` and `package-lock.json`.
`package.json` was edited manually, and package-lock was regenerated using NPM v8.19.3.
> release: Move dev dependencies

- README.md
> release: bump release

- .github/workflows/create-release.yaml
- package-lock.json
raise workflow to node18 and python3 to overcome competibility issues
> Raise workflow to node18 and python3

- README.md
> feat: new SM v2 API release

- examples/secrets-manager.v2.test.js
- secrets-manager/v2.ts
- test/integration/secrets-manager.v2.test.js
- test/unit/secrets-manager.v2.test.js
> patch: Adding get secret by name

- examples/secrets-manager.v2.test.js
- package-lock.json
- package.json
- secrets-manager/v2.ts
- test/integration/secrets-manager.v2.test.js
- test/unit/secrets-manager.v2.test.js
- Custom password generation policy for user-credentials secrets
- Fix service credentials secret (missing fields in response)
> Custom password generation policy for username password secrets

- examples/secrets-manager.v2.test.js
- secrets-manager/v2.ts
- test/integration/secrets-manager.v2.test.js
- test/unit/secrets-manager.v2.test.js
- Add List filters: `secret_types`, `match_all_labels`
- Add Expiration date field to `iam_credentials` and `service_credentials` API responses
> patch: API enhancements

- README.md
- package.json
- secrets-manager/v2.ts
Print expiration_date to secret's versions
> Print expiration_date to secret's versions

- README.md
- secrets-manager/v2.ts
add private cert intermediate rotate API
> patch: support for intermediate CA certificates rotation

- .eslintrc.js
- .github/dependabot.yml
- README.md
- examples/secrets-manager.v2.test.js
- package-lock.json
- package.json
- secrets-manager/v2.ts
- test/.eslintrc.js
- test/integration/secrets-manager-manual.v2.test.js
- test/integration/secrets-manager.v2.test.js
- test/resources/auth-helper.js
- test/unit/common.test.js
- test/unit/secrets-manager.v2.test.js
Imported certificate with managed CSR
> patch: Imported certificate with managed CSR

- README.md
- examples/secrets-manager.v2.test.js
- secrets-manager/v2.ts
- test/integration/secrets-manager.v2.test.js
- test/unit/secrets-manager.v2.test.js
Adding support for custom credentials.
> patch: custom credentials secret type
